creation_rules:
  - path_regex: test\.env$
    unencrypted_regex: "^(url|username)$"
    age: >-
      age1hrpdkvj7yh4clpxnjzmecwsdgs8kwfa9xjxq2j99ss9ca8c79qushjxled
  - path_regex: test\.json$
    unencrypted_regex: "^(url|username)$"
    age: >-
      age1hrpdkvj7yh4clpxnjzmecwsdgs8kwfa9xjxq2j99ss9ca8c79qushjxled
  - path_regex: test\.yaml$
    unencrypted_regex: "^(url|username)$"
    age: >-
      age1hrpdkvj7yh4clpxnjzmecwsdgs8kwfa9xjxq2j99ss9ca8c79qushjxled
